package io.github.yysf1949.rag.core.model;

/**
 * Origin of a generated {@link Answer}.
 *
 * <p>Design spec §11.1 — the QA chain walks
 * {@code CACHE → LLM → FALLBACK_RULE}; {@code AnswerSource} records which leg
 * actually produced the text. This drives the cache-hit-ratio metric and the
 * end-to-end trace MDC entry.</p>
 */
public enum AnswerSource {
    /** Returned verbatim from {@code rag:answer-cache:{tenant}:{queryHash}}. */
    CACHE,
    /** Generated by the LLM (DashScope qwen-plus / qwen-max). */
    LLM,
    /** LLM failed/timed out; concatenated retrieved chunks verbatim (spec §7.5). */
    FALLBACK_RULE
}