package io.github.yysf1949.rag.app.web;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.yysf1949.rag.app.config.BeansConfig;
import io.github.yysf1949.rag.core.model.Chunk;
import io.github.yysf1949.rag.core.model.ChunkStatus;
import io.github.yysf1949.rag.core.model.KbVersion;
import io.github.yysf1949.rag.core.model.PermissionMode;
import io.github.yysf1949.rag.core.port.VectorStore;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.MediaType;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

import java.time.Instant;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * End-to-end smoke for {@code POST /api/qa} in stub mode.
 *
 * <p>This is the "first mile" test — the user can run {@code mvn verify},
 * then start the app, then {@code curl} the same body and get the same
 * answer. No Redis, no DashScope, no LLM network calls — everything is
 * satisfied by the stub beans in {@code BeansConfig}, with one override
 * (a vector store pre-seeded with a chunk) so the cache-hit leg can be
 * exercised end-to-end.</p>
 */
@SpringBootTest
@AutoConfigureMockMvc
@TestPropertySource(properties = {
        "spring.main.web-application-type=servlet",
        "spring.data.redis.host=nonexistent",
        "spring.data.redis.port=0"
})
class RagControllerSmokeTest {

    @Autowired
    private MockMvc mvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void postQaReturnsStubbedAnswer() throws Exception {
        var body = Map.of(
                "userId", "alice",
                "sessionId", "sess-1",
                "rawText", "运费怎么退？",
                "permissionTags", List.of("ROLE_USER"),
                "topK", 5);

        mvc.perform(post("/api/qa")
                        .header("X-Tenant-Id", "tenant-A")
                        .header("X-Request-Id", "req-test-1")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(body)))
                .andExpect(status().isOk())
                .andExpect(header().string("X-Request-Id", "req-test-1"))
                .andExpect(jsonPath("$.tenantId").value("tenant-A"))
                .andExpect(jsonPath("$.source").exists())
                .andExpect(jsonPath("$.finalText").exists())
                .andExpect(jsonPath("$.latencyMs").exists());
    }

    @Test
    void missingTenantHeaderReturns401() throws Exception {
        var body = Map.of(
                "userId", "alice",
                "rawText", "test");

        mvc.perform(post("/api/qa")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(body)))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.error").value("missing_tenant"));
    }

    @Test
    void missingUserIdReturns400() throws Exception {
        var body = Map.of(
                "rawText", "test");

        mvc.perform(post("/api/qa")
                        .header("X-Tenant-Id", "tenant-A")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(body)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error").value("validation_failed"));
    }

    @Test
    void missingRawTextReturns400() throws Exception {
        var body = Map.of(
                "userId", "alice");

        mvc.perform(post("/api/qa")
                        .header("X-Tenant-Id", "tenant-A")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(body)))
                .andExpect(status().isBadRequest());
    }

    @Test
    void requestIdIsAutoGeneratedIfAbsent() throws Exception {
        var body = Map.of(
                "userId", "alice",
                "rawText", "test");

        mvc.perform(post("/api/qa")
                        .header("X-Tenant-Id", "tenant-A")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(body)))
                .andExpect(status().isOk())
                .andExpect(header().exists("X-Request-Id"));
    }

    @Test
    void cacheHitOnRepeatedQuery() throws Exception {
        // The pre-seeded vector store (see TestVectorStoreConfig below)
        // returns one matching chunk per call. First call: LLM, then
        // AnswerCache.put. Second call: cache hit.
        var body = Map.of(
                "userId", "alice",
                "rawText", "运费怎么退？",
                "permissionTags", List.of("ROLE_USER"));

        var first = mvc.perform(post("/api/qa")
                        .header("X-Tenant-Id", "tenant-cache-test")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(body)))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();
        var firstSource = objectMapper.readTree(first).get("source").asText();
        assertEquals("LLM", firstSource,
                "first call must come from the LLM leg, got: " + firstSource);

        mvc.perform(post("/api/qa")
                        .header("X-Tenant-Id", "tenant-cache-test")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(body)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.source").value("CACHE"));
    }

    /**
     * Test-only vector store that returns a single pre-seeded chunk per
     * search. Registered as {@code @Primary} so it wins over the
     * auto-registered {@code StubVectorStore} in {@link BeansConfig}.
     */
    @TestConfiguration
    static class TestVectorStoreConfig {

        @Bean
        @Primary
        public VectorStore seededVectorStore() {
            return new SeededVectorStore();
        }

        static class SeededVectorStore implements VectorStore {
            private final ConcurrentMap<String, Chunk> store = new ConcurrentHashMap<>();

            SeededVectorStore() {
                Chunk seed = new Chunk(
                        "seeded-1", "tenant-cache-test", "kb-1", "doc-1", "1",
                        "退款规则", "运费条款",
                        "运费退还规则：商品签收 7 日内可申请运费退款。",
                        new HashSet<>(Set.of("ROLE_USER")),
                        ChunkStatus.ACTIVE,
                        Instant.now(),
                        "https://docs.example.com/refund",
                        new float[16]);
                store.put(seed.chunkId(), seed);
            }

            @Override
            public int upsert(List<Chunk> chunks) {
                for (var c : chunks) store.put(c.chunkId(), c);
                return chunks.size();
            }

            @Override
            public int deleteByIds(String tenantId, String kbId, long kbVersion, List<String> chunkIds) {
                int n = 0;
                for (String id : chunkIds) if (store.remove(id) != null) n++;
                return n;
            }

            @Override
            public List<Chunk> search(
                    float[] queryVector,
                    String tenantId,
                    String kbId,
                    long kbVersion,
                    List<String> userPermissionTags,
                    PermissionMode permissionMode,
                    int topK) {
                return store.values().stream()
                        .filter(c -> c.tenantId().equals(tenantId))
                        .limit(topK)
                        .toList();
            }

            @Override
            public void publish(String tenantId, String kbId, long kbVersion) {}

            @Override
            public int deprecate(String tenantId, String kbId, long oldKbVersion) { return 0; }
        }
    }
}
